#!/usr/bin/env bash

# conditions for launching picom
if pgrep -u "$USER" -x picom &>/dev/null; then
  pkill -u "$USER" -x picom
  sleep 1.5
fi

# launch picom
picom -b --config "$HOME/.config/picom/picom.conf"
